### logout
POST http://localhost:8080/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImV4cCI6MTc1MjAzNTkwMiwiaWF0IjoxNzUyMDM1MDAyLCJyb2xlcyI6WyJ0YW11Il0sInRva2VuX3ZlcnNpb24iOiJmNzVkYzYwZC03NDc0LTQwZGEtYTBhZS02ODhiMDdiODhkYmUiLCJ1c2VyX2lkIjoiMDFKWlBQR0dRU1A0WUZBU1YwRUVQN0JOVDYifQ.6MOIi1cOMxz9ftNEb_RUTFmZcVC7WHtHLh-ZAgqxjTs

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "identifier": "irawankilmer@gmail.com",
  "password": "irawankilmer@gmail.com"
}

### register
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "irawankilmer",
  "email": "irawankilmer@gmail.com",
  "password": "irawankilmer@gmail.com",
  "profile": {
    "full_name": "Irawan Kilmer sejati"
  }
}