### logout
POST http://localhost:8080/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNzUyMDQ5MDE1LCJpYXQiOjE3NTIwNDgxMTUsInJvbGVzIjpbInN1cGVyIGFkbWluIl0sInRva2VuX3ZlcnNpb24iOiIxOWUwOGNlMC02OTAwLTQwY2QtODRlOS1hNjhlOTJhY2U1MGYiLCJ1c2VyX2lkIjoiMDFKWlEzOEc0VEs5RVMwS1dDWFgxMzJNRFgifQ.k3reFlEyFRSTVYmsk3yufC1NfCnR5OpKlnvL6DkJgTI

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "identifier": "supedmin",
  "password": ""
}

### register
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "irawankilmer",
  "email": "irawankilmer@gmail.com",
  "password": "irawankilmer@gmail.com",
  "profile": {
    "full_name": "Irawan Kilmer sejati"
  }
}