### Delete user
DELETE http://localhost:8080/api/users/01JZMY46PE40W3AR82N9R0HMC5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImV4cCI6MTc1MTk5MTU3NiwiaWF0IjoxNzUxOTkwNjc2LCJyb2xlcyI6WyJlZGl0b3IiXSwidG9rZW5fdmVyc2lvbiI6ImY5MzViZjU3LTA5NWMtNDM3Mi04OGI3LWQ2YjM4MWU5NWM4NiIsInVzZXJfaWQiOiIwMUpaTVk0NlBFNDBXM0FSODJOOVIwSE1DNSJ9.CLs4leAI9HrZrH0Kjs6t-PEYXh7BrXoB5lr155NjmzI

###
### Get User by ID
GET http://localhost:8080/api/users/01JZMY46PE40W3AR82N9R0HMC5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImV4cCI6MTc1MTk5MTU3NiwiaWF0IjoxNzUxOTkwNjc2LCJyb2xlcyI6WyJlZGl0b3IiXSwidG9rZW5fdmVyc2lvbiI6ImY5MzViZjU3LTA5NWMtNDM3Mi04OGI3LWQ2YjM4MWU5NWM4NiIsInVzZXJfaWQiOiIwMUpaTVk0NlBFNDBXM0FSODJOOVIwSE1DNSJ9.CLs4leAI9HrZrH0Kjs6t-PEYXh7BrXoB5lr155NjmzI

### Get Users
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImV4cCI6MTc1MTk5MTU3NiwiaWF0IjoxNzUxOTkwNjc2LCJyb2xlcyI6WyJlZGl0b3IiXSwidG9rZW5fdmVyc2lvbiI6ImY5MzViZjU3LTA5NWMtNDM3Mi04OGI3LWQ2YjM4MWU5NWM4NiIsInVzZXJfaWQiOiIwMUpaTVk0NlBFNDBXM0FSODJOOVIwSE1DNSJ9.CLs4leAI9HrZrH0Kjs6t-PEYXh7BrXoB5lr155NjmzI

### Create user
POST http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImV4cCI6MTc1MTk5MTU3NiwiaWF0IjoxNzUxOTkwNjc2LCJyb2xlcyI6WyJlZGl0b3IiXSwidG9rZW5fdmVyc2lvbiI6ImY5MzViZjU3LTA5NWMtNDM3Mi04OGI3LWQ2YjM4MWU5NWM4NiIsInVzZXJfaWQiOiIwMUpaTVk0NlBFNDBXM0FSODJOOVIwSE1DNSJ9.CLs4leAI9HrZrH0Kjs6t-PEYXh7BrXoB5lr155NjmzI
Content-Type: application/json

{
  "username": "ghania",
  "email": "ghania@gmail.com",
  "password": "ghania",
  "profile": {
    "full_name": "Saya ghania Reborn 6"
  },
  "roles": ["editor"]
}

###
### Username update
PATCH http://localhost:8080/api/users/01JZMY46PE40W3AR82N9R0HMC5/username
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImV4cCI6MTc1MTk5MTU3NiwiaWF0IjoxNzUxOTkwNjc2LCJyb2xlcyI6WyJlZGl0b3IiXSwidG9rZW5fdmVyc2lvbiI6ImY5MzViZjU3LTA5NWMtNDM3Mi04OGI3LWQ2YjM4MWU5NWM4NiIsInVzZXJfaWQiOiIwMUpaTVk0NlBFNDBXM0FSODJOOVIwSE1DNSJ9.CLs4leAI9HrZrH0Kjs6t-PEYXh7BrXoB5lr155NjmzI
Content-Type: application/json

{
  "username": "sipirda"
}

###
### Email update
PATCH http://localhost:8080/api/users/01JZMY46PE40W3AR82N9R0HMC5/email
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImV4cCI6MTc1MTk5MTU3NiwiaWF0IjoxNzUxOTkwNjc2LCJyb2xlcyI6WyJlZGl0b3IiXSwidG9rZW5fdmVyc2lvbiI6ImY5MzViZjU3LTA5NWMtNDM3Mi04OGI3LWQ2YjM4MWU5NWM4NiIsInVzZXJfaWQiOiIwMUpaTVk0NlBFNDBXM0FSODJOOVIwSE1DNSJ9.CLs4leAI9HrZrH0Kjs6t-PEYXh7BrXoB5lr155NjmzI
Content-Type: application/json

{
  "email": "gagaklumayung@gmail.com"
}

###
### Password reset
PATCH http://localhost:8080/api/users/01JZMY46PE40W3AR82N9R0HMC5/reset-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImV4cCI6MTc1MTk5MTU3NiwiaWF0IjoxNzUxOTkwNjc2LCJyb2xlcyI6WyJlZGl0b3IiXSwidG9rZW5fdmVyc2lvbiI6ImY5MzViZjU3LTA5NWMtNDM3Mi04OGI3LWQ2YjM4MWU5NWM4NiIsInVzZXJfaWQiOiIwMUpaTVk0NlBFNDBXM0FSODJOOVIwSE1DNSJ9.CLs4leAI9HrZrH0Kjs6t-PEYXh7BrXoB5lr155NjmzI
Content-Type: application/json

###
### Roles update
PATCH http://localhost:8080/api/users/01JZMY46PE40W3AR82N9R0HMC5/roles-update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImV4cCI6MTc1MTk5MTU3NiwiaWF0IjoxNzUxOTkwNjc2LCJyb2xlcyI6WyJlZGl0b3IiXSwidG9rZW5fdmVyc2lvbiI6ImY5MzViZjU3LTA5NWMtNDM3Mi04OGI3LWQ2YjM4MWU5NWM4NiIsInVzZXJfaWQiOiIwMUpaTVk0NlBFNDBXM0FSODJOOVIwSE1DNSJ9.CLs4leAI9HrZrH0Kjs6t-PEYXh7BrXoB5lr155NjmzI
Content-Type: application/json

{
  "roles": ["penulis"]
}