### Delete user
DELETE http://localhost:8080/api/users/01JZMY46PE40W3AR82N9R0HMC5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNzUyMDUyODYxLCJpYXQiOjE3NTIwNTE5NjEsInJvbGVzIjpbInN1cGVyIGFkbWluIl0sInRva2VuX3ZlcnNpb24iOiI2ZTc5ZmYzMC0zNzJmLTQ5OTEtOWEyMS00ZWM1MjRjNTkyNDgiLCJ1c2VyX2lkIjoiMDFKWlE2WFhFTVk3M1FYWE45SEFXTTQ4UDIifQ.DH6B9NS9cIgx01Z4fv4F2fUhzfgJ6xIZNTSWf9qVUNE

###
### Get User by ID
GET http://localhost:8080/api/users/01JZMY46PE40W3AR82N9R0HMC5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNzUyMDUyODYxLCJpYXQiOjE3NTIwNTE5NjEsInJvbGVzIjpbInN1cGVyIGFkbWluIl0sInRva2VuX3ZlcnNpb24iOiI2ZTc5ZmYzMC0zNzJmLTQ5OTEtOWEyMS00ZWM1MjRjNTkyNDgiLCJ1c2VyX2lkIjoiMDFKWlE2WFhFTVk3M1FYWE45SEFXTTQ4UDIifQ.DH6B9NS9cIgx01Z4fv4F2fUhzfgJ6xIZNTSWf9qVUNE

### Get Users
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNzUyMDUyODYxLCJpYXQiOjE3NTIwNTE5NjEsInJvbGVzIjpbInN1cGVyIGFkbWluIl0sInRva2VuX3ZlcnNpb24iOiI2ZTc5ZmYzMC0zNzJmLTQ5OTEtOWEyMS00ZWM1MjRjNTkyNDgiLCJ1c2VyX2lkIjoiMDFKWlE2WFhFTVk3M1FYWE45SEFXTTQ4UDIifQ.DH6B9NS9cIgx01Z4fv4F2fUhzfgJ6xIZNTSWf9qVUNE

### Create user
POST http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNzUyMDUyODYxLCJpYXQiOjE3NTIwNTE5NjEsInJvbGVzIjpbInN1cGVyIGFkbWluIl0sInRva2VuX3ZlcnNpb24iOiI2ZTc5ZmYzMC0zNzJmLTQ5OTEtOWEyMS00ZWM1MjRjNTkyNDgiLCJ1c2VyX2lkIjoiMDFKWlE2WFhFTVk3M1FYWE45SEFXTTQ4UDIifQ.DH6B9NS9cIgx01Z4fv4F2fUhzfgJ6xIZNTSWf9qVUNE
Content-Type: application/json

{
  "email": "irawankilmer@gmail.com",
  "roles": ["editor"]
}

###
### Email update
PATCH http://localhost:8080/api/users/01JZMY46PE40W3AR82N9R0HMC5/email
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNzUyMDUyODYxLCJpYXQiOjE3NTIwNTE5NjEsInJvbGVzIjpbInN1cGVyIGFkbWluIl0sInRva2VuX3ZlcnNpb24iOiI2ZTc5ZmYzMC0zNzJmLTQ5OTEtOWEyMS00ZWM1MjRjNTkyNDgiLCJ1c2VyX2lkIjoiMDFKWlE2WFhFTVk3M1FYWE45SEFXTTQ4UDIifQ.DH6B9NS9cIgx01Z4fv4F2fUhzfgJ6xIZNTSWf9qVUNE
Content-Type: application/json

{
  "email": "gagaklumayung@gmail.com"
}

###
### Roles update
PATCH http://localhost:8080/api/users/01JZMY46PE40W3AR82N9R0HMC5/roles-update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNzUyMDUyODYxLCJpYXQiOjE3NTIwNTE5NjEsInJvbGVzIjpbInN1cGVyIGFkbWluIl0sInRva2VuX3ZlcnNpb24iOiI2ZTc5ZmYzMC0zNzJmLTQ5OTEtOWEyMS00ZWM1MjRjNTkyNDgiLCJ1c2VyX2lkIjoiMDFKWlE2WFhFTVk3M1FYWE45SEFXTTQ4UDIifQ.DH6B9NS9cIgx01Z4fv4F2fUhzfgJ6xIZNTSWf9qVUNE
Content-Type: application/json

{
  "roles": ["penulis"]
}