### Delete user
DELETE http://localhost:8080/api/users/01JZZPW0CEEVKKSDPKBA63CJ4P
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNzUyMzk3NDA2LCJpYXQiOjE3NTIzOTY1MDYsInJvbGVzIjpbInN1cGVyIGFkbWluIl0sInRva2VuX3ZlcnNpb24iOiIwZTYxZTFlNy1iNzIzLTRhYjktYWEyZi0yOWQyMjlmNTZiOTAiLCJ1c2VyX2lkIjoiMDFLMDFGRFpTUjRUWTM2WURLODJKQVhSM1AifQ.Eyda_dJ8UFECAVSBmjlJmS_Cvjl1gZUKs__ZibnpAuQ
###
### Get User by ID
GET http://localhost:8080/api/users/01JZZPW0CEEVKKSDPKBA63CJ4P
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNzUyMzk3NDA2LCJpYXQiOjE3NTIzOTY1MDYsInJvbGVzIjpbInN1cGVyIGFkbWluIl0sInRva2VuX3ZlcnNpb24iOiIwZTYxZTFlNy1iNzIzLTRhYjktYWEyZi0yOWQyMjlmNTZiOTAiLCJ1c2VyX2lkIjoiMDFLMDFGRFpTUjRUWTM2WURLODJKQVhSM1AifQ.Eyda_dJ8UFECAVSBmjlJmS_Cvjl1gZUKs__ZibnpAuQ

### Get Users
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNzUyMzk3NDA2LCJpYXQiOjE3NTIzOTY1MDYsInJvbGVzIjpbInN1cGVyIGFkbWluIl0sInRva2VuX3ZlcnNpb24iOiIwZTYxZTFlNy1iNzIzLTRhYjktYWEyZi0yOWQyMjlmNTZiOTAiLCJ1c2VyX2lkIjoiMDFLMDFGRFpTUjRUWTM2WURLODJKQVhSM1AifQ.Eyda_dJ8UFECAVSBmjlJmS_Cvjl1gZUKs__ZibnpAuQ


### Create user
POST http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNzUyMzk3NDA2LCJpYXQiOjE3NTIzOTY1MDYsInJvbGVzIjpbInN1cGVyIGFkbWluIl0sInRva2VuX3ZlcnNpb24iOiIwZTYxZTFlNy1iNzIzLTRhYjktYWEyZi0yOWQyMjlmNTZiOTAiLCJ1c2VyX2lkIjoiMDFLMDFGRFpTUjRUWTM2WURLODJKQVhSM1AifQ.Eyda_dJ8UFECAVSBmjlJmS_Cvjl1gZUKs__ZibnpAuQ

{
  "full_name": "Irawan Kilmer",
  "email": "irawankilmer@gmail.com",
  "roles": ["editor"]
}

###
### Email update
PATCH http://localhost:8080/api/users/01JZZPW0CEEVKKSDPKBA63CJ4P/email
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNzUyMzk3NDA2LCJpYXQiOjE3NTIzOTY1MDYsInJvbGVzIjpbInN1cGVyIGFkbWluIl0sInRva2VuX3ZlcnNpb24iOiIwZTYxZTFlNy1iNzIzLTRhYjktYWEyZi0yOWQyMjlmNTZiOTAiLCJ1c2VyX2lkIjoiMDFLMDFGRFpTUjRUWTM2WURLODJKQVhSM1AifQ.Eyda_dJ8UFECAVSBmjlJmS_Cvjl1gZUKs__ZibnpAuQ

{
  "email": "gagaklumayung@gmail.com"
}

###
### Roles update
PATCH http://localhost:8080/api/users/01JZZPW0CEEVKKSDPKBA63CJ4P/roles-update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNzUyMzk3NDA2LCJpYXQiOjE3NTIzOTY1MDYsInJvbGVzIjpbInN1cGVyIGFkbWluIl0sInRva2VuX3ZlcnNpb24iOiIwZTYxZTFlNy1iNzIzLTRhYjktYWEyZi0yOWQyMjlmNTZiOTAiLCJ1c2VyX2lkIjoiMDFLMDFGRFpTUjRUWTM2WURLODJKQVhSM1AifQ.Eyda_dJ8UFECAVSBmjlJmS_Cvjl1gZUKs__ZibnpAuQ

{
  "roles": ["penulis", "editor"]
}