### Verify Register Resend
POST http://localhost:8080/api/auth/verify-register-resend



### Email verify
POST http://localhost:8080/api/auth/verify-email
Content-Type: application/json

{
  "token": "cc2dad459094e7996b3c7aebbe09f0a682866ffea3b312fa82b8158b582f9a4eec30c0af4ba5af5728402578d88c0705fb007bb33d79a9520738228e78caf740"
}


### Verify Register
POST http://localhost:8080/api/auth/verify-register?token=a356a935359f4d8d8f6a272a9f5541f3fa5d20bb89c7bc16927a7f42cdd1f6c29539768520c2c6a31af32eb4ecf7c0f7ef5148e3c1b857ff&email=irawankilmer@gmail.com
Content-Type: application/json

{
  "username": "superadmin",
  "password": "superadmin",
  "password_confirm": "sasasa"
}