### Email verify
GET http://localhost:8080/api/auth/verify-email?token=0274dd49832f85824d420938f6e7db8c14c9c0f9353c48cb0e728607f4bcad96

### Verify Register
POST http://localhost:8080/api/auth/verify-register?token=a356a935359f4d8d8f6a272a9f5541f3fa5d20bb89c7bc16927a7f42cdd1f6c29539768520c2c6a31af32eb4ecf7c0f7ef5148e3c1b857ff&email=irawankilmer@gmail.com
Content-Type: application/json

{
  "username": "superadmin",
  "password": "superadmin",
  "password_confirm": "sasasa"
}