CREATE TABLE users(
  id VARCHAR(26) NOT NULL PRIMARY KEY,
  username VARCHAR(255) UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255),
  token_version VARCHAR(36) NOT NULL,
  email_verified BOOLEAN NOT NULL DEFAULT false,
  created_by_admin BOOLEAN NOT NULL DEFAULT true,
  google_id VARCHAR(255),

  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;