CREATE TABLE profiles(
  id VARCHAR(26) NOT NULL PRIMARY KEY,
  user_id VARCHAR(26) NOT NULL UNIQUE,
  full_name VARCHAR(125) NOT NULL,
  address TEXT,
  gender ENUM("laki-laki", "perempuan"),
  image VARCHAR(255),

  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;